### ISSUE TITLE
问题咨询

### ISSUE THREAD

**Issue by wangbiao92** [2bsunshine4u/MapMatching#1]
你好，我是福州大学的研一学生，现在在搞地图匹配的课题，有幸在github上看到你的博文，因为刚接触python，对你的源码不是很清楚，能否发一份你写的论文，借我参考下（只是作为学术研究）

**Comment by ShuaiShao93** [comment]
好的，你邮箱多少？我发给你吧

**Comment by wangbiao92** [comment]
我的邮箱是516947892@qq.com，非常谢谢

**Comment by wangbiao92** [comment]
你好，我想问下，在UI模块中traj_file.append("oneMonthData/oneMonth_967790112791.txt")，这个车辆数据文件的格式是什么样的？非常感谢！

**Comment by ShuaiShao93** [comment]
像这样的：
{"latitude":39.83654,"devicesn":"967790112421","speed":0,"longitude":116.37153333333332,"direction":119,"timestamp":1425177688}
{"latitude":39.836528333333334,"devicesn":"967790112421","speed":0,"longitude":116.37171166666667,"direction":80,"timestamp":1425177694}
{"latitude":39.836595,"devicesn":"967790112421","speed":15.67,"longitude":116.37185,"direction":68,"timestamp":1425177697}
{"latitude":39.83672,"devicesn":"967790112421","speed":12.67,"longitude":116.37214833333334,"direction":82,"timestamp":1425177702}
{"latitude":39.836705,"devicesn":"967790112421","speed":9.01,"longitude":116.37233666666667,"direction":86,"timestamp":1425177704}
{"latitude":39.836585,"devicesn":"967790112421","speed":18.74,"longitude":116.37248,"direction":161,"timestamp":1425177709}

**Comment by wangbiao92** [comment]
真的非常谢谢！！！

**Comment by simba2icac** [comment]
你好，我是东北大学研一的学生，请问你的论文能发我一份嘛，纯属学术研究，谢谢

**Comment by simba2icac** [comment]
邮箱ceoicac@163.com

**Comment by ShuaiShao93** [comment]
已发请查收

**Comment by billy12323** [comment]
学长您好，通过阅读代码，我对您如何实现高效的地图匹配思路理解的还不够，能否将您的论文也发我一份，邮箱84352093@qq.com，仅学术学习使用，谢谢！

**Comment by ShuaiShao93** [comment]
已发，当年本科瞎写的，将就看吧。。
